# Generated by Django 4.2.2 on 2023-10-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aadhar_card_number', models.CharField(max_length=12, unique=True)),
                ('entity_type', models.CharField(choices=[('farmer', 'Farmer'), ('wholesaler', 'Wholesaler'), ('consumer', 'Consumer')], max_length=20)),
            ],
        ),
    ]
