# Generated by Django 4.2.2 on 2023-10-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersco', '0002_farmerlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aadhar_card_number', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WholesalerLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aadhar_card_number', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='farmerlogin',
            name='entity_type',
        ),
    ]
